version: "3.7"
services:
  frontend-service:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    env_file:
      - frontend/.env
    ports:
      - "5000:5000"
    links:
      - backend-service
      - redis-service
  backend-service:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    expose:
      - 8000
    ports:
      - "8000:8000"
  redis-service:
    image: redis:6-alpine3.14
    expose:
      - 6379
    ports:
      - "6379:6379"

