apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  BACKEND_HOST: "backend-service"
  BACKEND_PORT: "8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-deployment
          image: dock-reg-0001.ml/asset-app:0.1.4
          imagePullPolicy: Always
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BACKEND_HOST
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BACKEND_PORT
          ports:
            - containerPort: 5000
#          readinessProbe:
#            httpGet:
#              path: /ready
#              port: 5000
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 5000
#            initialDelaySeconds: 3
#            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 5000
      port: 5000
  selector:
    app: frontend